#!/bin/sh

GIDLIST="-g 00:00:00:00:00:00:02:00"
FILTERSPEC=tubby_fspec
SEARCHLET=tsearch.so
CONFBASE=./bench_conf
RATES="0 10  20 30 40 50 60 70 80 90 100"
PROGRAM=../snap_bench
RUNS="1 2 3"

for run in $RUNS; do
	run_ext=_r$run
	echo $run_ext
	for rate in $RATES; do 
		conf=./bench_conf_$rate
	    logname=4d_0_dark_sel_1g_$rate$run_ext
		specfile=dark_sel_fspec
		$PROGRAM -s $SEARCHLET -f $specfile -c $conf $rate $GIDLIST > $logname
	    logname=4d_0_dark_nsel_1g_$rate$run_ext
		specfile=dark_nsel_fspec
		$PROGRAM -s $SEARCHLET -f $specfile -c $conf $rate $GIDLIST > $logname
	    logname=4d_0_tubby_sel_1g_$rate$run_ext
		specfile=tubby_sel_fspec
		$PROGRAM -s $SEARCHLET -f $specfile -c $conf $rate $GIDLIST > $logname
	done
done


